# Generated by Django 5.2.6 on 2025-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='邮箱')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('login_date', models.DateField(null=True, verbose_name='最后登录时间')),
                ('status', models.IntegerField(null=True, verbose_name='账号状态（0:正常 1:停用）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uodate_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
