# Generated by Django 5.2.6 on 2025-09-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='SysUser',
        ),
    ]
